<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">


    <xacro:property name="chassis_length" value="0.335"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    
      <!-- Wheel parameters -->
      <xacro:property name="wheel_offset_x" value="0.226"/>
      <xacro:property name="wheel_offset_y" value="0.1485"/>
      <xacro:property name="wheel_offset_z" value="0.01"/>


      <!-- Constants -->
      <xacro:property name="PI" value="3.1415926535897931" />
      <xacro:property name="wheel_radius" value="0.033"/>
      <xacro:property name="wheel_height" value="0.026"/>
      <xacro:property name="wheel_mass" value="0.05"/>
      <!-- Simple Macro to calculate inertia -->
      <xacro:macro name="cylinder_inertia" params="m r h">
          <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                  iyy="${m*r*r/2}" iyz = "0"
                  izz="${m*(3*r*r+h*h)/12}" />
      </xacro:macro>

      
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>


     <!-- BASE LINK -->

     <link name="base_link">

     </link>
 
     <!-- BASE_FOOTPRINT LINK -->
 
     <joint name="base_footprint_joint" type="fixed">
         <parent link="base_link"/>
         <child link="base_footprint"/>
         <origin xyz="0 0 0" rpy="0 0 0"/>
     </joint>
 
     <link name="base_footprint">
     </link>


     <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
       
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>









   



     <!-- WHEEL LINK -->

     <xacro:macro name="omni_wheel" params="prefix parent *origin reflect">

    <link name="${prefix}_wheel_link">
      <visual>
            <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            <geometry>
                <cylinder length="${wheel_height}" radius="${wheel_radius}" />
            </geometry>
      </visual>

      <collision>
				<origin xyz="0 0 0" rpy="${PI/2} 0 0" />
        <geometry>
					<cylinder length="${wheel_height}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <inertial>
        <mass value="${wheel_mass}" />
        <origin xyz="0 0 0" />
        <cylinder_inertia  m="${wheel_mass}" r="${wheel_radius}" h="${wheel_height}" />
      </inertial>
    </link>


    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${prefix}_wheel_link"/>
      <xacro:insert_block name="origin" />
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <gazebo reference="${prefix}_wheel_link">
		<mu1 value="1.0"/>
		<mu2 value="1.0"/>
		<kp value="10000000.0" />
		<kd value="1.0" />
		<fdir1 value="1 0 0"/>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

  </xacro:macro>





    <!-- Wheel parameters -->
	<xacro:property name="wheel_offset_x" value="0.2225" />    <!-- x,y,z in translation from base_link to the center of the wheel -->
	<xacro:property name="wheel_offset_y" value="0.2045" />
	<xacro:property name="wheel_offset_z" value="0.0" />

	<xacro:macro name="robot">
		

		<xacro:omni_wheel prefix="summit_front_right" parent="base_link" reflect="false">
			<origin xyz="${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
		</xacro:omni_wheel>

		<xacro:omni_wheel prefix="summit_front_left" parent="base_link" reflect="true">
			<origin xyz="${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
		</xacro:omni_wheel>

		<xacro:omni_wheel prefix="summit_back_left" parent="base_link" reflect="true">
			<origin xyz="-${wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
		</xacro:omni_wheel>

		<xacro:omni_wheel prefix="summit_back_right" parent="base_link" reflect="false">
			<origin xyz="-${wheel_offset_x} -${wheel_offset_y} ${wheel_offset_z}" rpy="0 0 0"/>
		</xacro:omni_wheel>


   </xacro:macro>

   <xacro:robot/>

    
</robot>